version: '3.7'
services:
  afpd:
    container_name: afpd
    image: cptactionhank/netatalk
    # logging:
    #   driver: "none"
    ports:
      - "549:548"
    volumes:
      #- ${WORKSPACE_PATH}/projects:/home/www/projects  # UNIX only
      - data:/home/www/data  # MAC only
      - ${WORKSPACE_PATH}/env/config/afpd/afp.conf:/etc/afp.conf
    environment:
      - AFP_USER=www
      - AFP_PASSWORD=balance08
      - AFP_UID=5353
      - AFP_GID=5353
    networks:
      - frontend

volumes:                 # MAC only
  data:                  # MAC only
    name: data           # MAC only

networks:
  frontend:
    name: frontend