version: '3'
services:
  cloud9:
    container_name: cloud9
    image: hoadx/cloud9
    ports:
      - "8000:8000"
    environment:
      USERNAME:
      PASSWORD:
    volumes:
      - ${WORKSPACE_PATH}/projects:/workspace   # UNIX only
      #- data:/workspace   # MAC only
      - ~/.ssh:/root/.ssh
    networks:
      - default