version: '3'
services:
  cloud9:
    container_name: cloud9
    image: hoadx/cloud9
    ports:
      - "8000:8000"
    environment:
      USERNAME:
      PASSWORD:
    volumes:
      #- ../../projects:/workspace
      - data-volume:/workspace
      - ~/.ssh:/root/.ssh

volumes:
  data-volume:
    driver: local