version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.5
    # logging:
    #   driver: "none"
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${WORKSPACE_PATH}/elasticsearch/7.17.5/plugins:/usr/share/elasticsearch/plugins
    network_mode: "bridge"
