version: '3.7'
services:
  goaccess:
    container_name: goaccess
    image: allinurl/goaccess
    # logging:
    #   driver: "none"
    ports:
      - "7890:7890"
    volumes:
      - ${WORKSPACE_PATH}/env/config/goaccess/:/srv/data
      - ${WORKSPACE_PATH}/projects/others:/srv/report   # output /srv/report/goaccess.html
      - ${WORKSPACE_PATH}/log:/srv/logs
#    command: ["goaccess", "--no-global-config", "--real-time-html", "--config-file=/srv/data/goaccess.conf", "--log-file=/srv/logs/access.log"]
    network_mode: "bridge"