version: '3'
services:
  goaccess:
    container_name: goaccess
    image: allinurl/goaccess
    ports:
      - "7890:7890"
    volumes:
      - ../config/goaccess/:/srv/data
      - ../../projects/others:/srv/report   # output /srv/report/goaccess.html
      - ../../log:/srv/logs
#    command: ["goaccess", "--no-global-config", "--real-time-html", "--config-file=/srv/data/goaccess.conf", "--log-file=/srv/logs/access.log"]
