version: '3'
services:
  letsencrypt:
    container_name: letsencrypt
    image: hoadx/letsencrypt
  #  ports:
  #    - "80:80"
  #    - "443:443"
    volumes:
      - ${WORKSPACE_PATH}/letsencrypt/.well-known:/var/.well-known
      - ${WORKSPACE_PATH}/ssl:/etc/letsencrypt
    networks:
      - default