version: '3.7'
services:
  letsencrypt:
    container_name: letsencrypt
    image: hoadx/letsencrypt
    # logging:
    #   driver: "none"
  #  ports:
  #    - "80:80"
  #    - "443:443"
    volumes:
      - letsencrypt:/var/.well-known
      - ${WORKSPACE_PATH}/ssl:/etc/letsencrypt
    network_mode: "bridge"

volumes:
  letsencrypt:
    name: letsencrypt