version: '3'
services:
  letsencrypt:
    container_name: letsencrypt
    image: hoadx/letsencrypt
  #  ports:
  #    - "80:80"
  #    - "443:443"
    volumes:
      - ../letsencrypt/.well-known:/var/.well-known
      - ../ssl:/etc/letsencrypt
