version: '3'
services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    volumes:
        - ${WORKSPACE_PATH}/mailhog/storage:/mnt/storage
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/mnt/storage
    networks:
      - default
