version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/dbdump:/dbdump
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    environment:
      #- MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=balance08
    networks:
      - default
