version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    # logging:
    #   driver: "none"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ${WORKSPACE_PATH}/mysql/dbdump:/dbdump
      - ${WORKSPACE_PATH}/env/config/mysql/conf.d:/etc/mysql/conf.d
    environment:
      #- MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=balance08
    network_mode: "bridge"

volumes:
  mysql:
    name: mysql