version: '3'
services:
  nginx:
    container_name: nginx
    image: hoadx/nginx
    ports:
      - "80:80"
    volumes:
      - ${WORKSPACE_PATH}/env/config/nginx/conf.d:/etc/nginx/conf.d
      - ${WORKSPACE_PATH}/env/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WORKSPACE_PATH}/log/nginx:/var/log/nginx
      - ${WORKSPACE_PATH}/projects:/var/www    # UNIX only
      #- data:/var/www     # MAC only
    networks:
      - default
