version: '3'
services:
  nginx:
    container_name: nginx
    image: hoadx/nginx
    ports:
      - "80:80"
    volumes:
      - ../config/nginx/conf.d:/etc/nginx/conf.d
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../log/nginx:/var/log/nginx
      - ../../projects:/var/www
    networks:
      - default