version: '3.7'
services:
  odoo:
    image: odoo:13
    container_name: odoo
    ports:
      - "8069:8069"
    environment:
    - HOST=postgres
    - USER=odoo
    - PASSWORD=odoo
    volumes:
      - odoo:/var/lib/odoo

volumes:
  odoo:
    name: odoo
