version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
      #restart: unless-stopped
    # logging:
    #   driver: "none"
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    network_mode: "bridge"

volumes:
  portainer:
    name: portainer
