version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    # logging:
    #   driver: "none"
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - default

volumes:
  portainer:
    name: portainer