version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      #- POSTGRES_DB=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
