version: '3.7'
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    # logging:
    #   driver: "none"
    ports:
      - "443:443"
    environment:
      - NGINX_HOST=proxy.server
      - NGINX_PORT=80
    volumes:
      - ${WORKSPACE_PATH}/env/config/proxy/conf.d:/etc/nginx/conf.d
    network_mode: "bridge"
    command: /bin/sh -c "nginx -g 'daemon off;'"