version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:6-alpine
    # logging:
    #   driver: "none"
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    network_mode: "bridge"

volumes:
  redis:
    name: redis
