version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:alpine
    # logging:
    #   driver: "none"
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - default

volumes:
  redis:
    name: redis