version: '3'
services:
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      #- ${WORKSPACE_PATH}/projects:/home/www/projects  # UNIX only
      - data:/home/www/data  # MAC only
      #- ${WORKSPACE_PATH}/env/config/afpd/afp.conf:/etc/afp.conf
    environment:
#      - USER="www balance08 5353 www 5353"
      - USERID=5353
      - GROUPID=5353
      - SHARE="Projects /home/www/data yes no yes all"
    command: ['-p', '-n']
    networks:
      - default

volumes:                 # MAC only
  data:                  # MAC only
    external: true       # MAC only
  database:              # MAC only
    external: true       # MAC only
