version: '3.7'
services:
  samba:
    container_name: samba
    image: dperson/samba
    # logging:
    #   driver: "none"
    ports:
          - "137:137/udp"
          - "138:138/udp"
          - "139:139"
          - "445:445"
    volumes:
      #- ${WORKSPACE_PATH}/projects:/home/www/projects  # UNIX only
      - data:/home/www/data  # MAC only
      #- ${WORKSPACE_PATH}/env/config/afpd/afp.conf:/etc/afp.conf
    environment:
#      - USER="www balance08 5353 www 5353"
      - USERID=5000
      - GROUPID=5000
      - RECYCLE=1
#      - NMBD=1
      - SHARE="Projects /home/www/data yes no yes all"
    command: ['-p', '-n']
      #network_mode: "bridge"
      #    network_mode: "host"

volumes:                 # MAC only
  data:                  # MAC only
    name: data
