version: '3'
services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    ports:
      - "23:22"
    volumes:
      - ${WORKSPACE_PATH}/projects:/home/www/projects  # UNIX only
      #- data:/home/www/projects  # MAC only
      - ${WORKSPACE_PATH}/env/config/sftp/users.conf:/etc/sftp-users.conf:ro
    networks:
      - default
