version: '3.7'
services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    # logging:
    #   driver: "none"
    ports:
      - "23:22"
    volumes:
      #- ${WORKSPACE_PATH}/projects:/home/www/projects  # UNIX only
      - data:/home/www/data  # MAC only
      - ${WORKSPACE_PATH}/env/config/sftp/users.conf:/etc/sftp-users.conf:ro
    networks:
      - default

volumes:                 # MAC only
  data:                  # MAC only
    name: data