version: '3.7'
services:
  socat:
    container_name: socat
    image: alpine/socat
    # logging:
    #   driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    network_mode: "bridge"