version: '3.7'
services:
    orchestra:
#        restart: unless-stopped
        image: ezka77/xen-orchestra-ce:latest
        container_name: XO_server
        ports:
            - "8000:8000"
            - "8443:8443"
        depends_on:
            - redis
        environment:
            - DEBUG=xo:main
            - NODE_ENV=production
            - XOA_PLAN=5
            - XO_HTTP_REDIRECTTOHTTPS=true
            - XO_HTTP_LISTEN_PORT=8000
            - XO_HTTPS_LISTEN_PORT=8443
            - XO_HTTPS_LISTEN_AUTOCERT=true
        #privileged: true
        # SYS_ADMIN should be enough capability to use NFS mount
        cap_add:
            - SYS_ADMIN
        volumes:
            - xo-server:/storage
        logging: &logging
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "2"
    redis:
#        restart: unless-stopped
        container_name: XO_redis
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - xo_redis:/data
#        logging:
#            <<: *logging
volumes:
  xo_redis:
    name: xo_redis
  xo-server:
    name: xo-server
