version: '3'
services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    volumes:
        - ../mailhog/email:/mnt/storage
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/mnt/storage

  php-fpm:
    container_name: php-fpm
    image: hoadx/php:7.0-magento
    ports:
      - "9000:9000"
    volumes:
      - ./config/phpfpm/magento.php.ini:/etc/php.d/zzmagento.php.ini
      - ./config/phpfpm/ioncube.php.ini:/etc/php.d/00ioncube.php.ini
      - ../projects:/var/www

  nginx:
    container_name: nginx
    image: hoadx/nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../projects:/var/www
    depends_on:
      - php-fpm

  # mysql:
  #   container_name: mysql
  #   image: mysql:5.6
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ../mysql/data:/var/lib/mysql
  #     - ../mysql/dbdump:/dbdump
  #     - ./config/mysql/conf.d:/etc/mysql/conf.d
  #   environment:
  #     #- MYSQL_RANDOM_ROOT_PASSWORD=yes
  #     - MYSQL_ROOT_PASSWORD=balance08
