version: '3'
services:
  nginx:
    container_name: nginx
    image: registry.docker.balancenet.com.au:5000/library/nginx-web:1.8-2.0.0
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../projects:/var/www
    depends_on:
      - php-fpm
