version: '3'
services:
  nginx:
    container_name: nginx
    image: hoadx/nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../projects:/var/www
    depends_on:
      - php-fpm
