version: '3'
services:
  mysql:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer/data:/data
