version: '3'
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "443:443"
    environment:
      - NGINX_HOST=proxy.server
      - NGINX_PORT=80
    volumes:
      - ./config/proxy/conf.d:/etc/nginx/conf.d
    command: /bin/sh -c "nginx -g 'daemon off;'"

