version: '3'
services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    ports:
      - "22:22"
    volumes:
      - ../projects:/home/www/projects
    command: user:password:5353:5353
