version: '3'
services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    ports:
      - "23:22"
    volumes:
      - ../projects:/home/www/projects
      - ./config/sftp/users.conf:/etc/sftp-users.conf:ro
